In [ ]:
import pandas as pd

id_cols = ['flight_id', 'timestamp']
df = pd.read_parquet("EGLL_dataset.parquet.gz",columns=id_cols)
df

        flight_id                 timestamp
2    AAL136_37370 2019-11-06 13:05:36+00:00
3    AAL136_37370 2019-11-06 13:05:39+00:00
4    AAL136_37370 2019-11-06 13:05:42+00:00
5    AAL136_37370 2019-11-06 13:05:45+00:00
6    AAL136_37370 2019-11-06 13:05:48+00:00
..            ...                       ...
496  VLG901P_1286 2019-10-18 06:11:09+00:00
497  VLG901P_1286 2019-10-18 06:11:12+00:00
498  VLG901P_1286 2019-10-18 06:11:15+00:00
499  VLG901P_1286 2019-10-18 06:11:18+00:00
500  VLG901P_1286 2019-10-18 06:11:21+00:00

[18028280 rows x 2 columns]

In [3]:
groups = df.groupby('flight_id',sort=False)

groups.describe()

             timestamp                                    \
                 count                              mean
flight_id
AAL136_37370       354  2019-11-06 13:14:25.500000+00:00
AAL38_36464        401         2019-10-10 06:26:42+00:00
AAL50_36740        491  2019-11-28 09:02:39.782077+00:00
AAL104_36539       528  2019-10-15 10:25:13.500000+00:00
AAL142_37423       381         2019-10-16 20:29:42+00:00
...                ...                               ...
VLG7104_1397       295         2019-10-05 18:13:48+00:00
VOR09_25067        423  2019-11-30 00:24:02.943262+00:00
VLG7104_1400       486  2019-10-09 18:10:04.500000+00:00
WGT8H_2180         409         2019-11-15 14:20:03+00:00
VLG901P_1286       496  2019-10-18 05:58:57.332661+00:00

                                                                           \
                                    min                               25%
flight_id
AAL136_37370  2019-11-06 13:05:36+00:00  2019-11-06 13:10:00.750000+00:00
AAL38_36464   2019-10-10 06:16:42+00:00         2019-10-10 06:21:42+00:00
AAL50_36740   2019-11-28 08:50:15+00:00  2019-11-28 08:56:22.500000+00:00
AAL104_36539  2019-10-15 10:12:03+00:00  2019-10-15 10:18:38.250000+00:00
AAL142_37423  2019-10-16 20:20:12+00:00         2019-10-16 20:24:57+00:00
...                                 ...                               ...
VLG7104_1397  2019-10-05 18:06:27+00:00  2019-10-05 18:10:07.500000+00:00
VOR09_25067   2019-11-30 00:13:24+00:00  2019-11-30 00:18:46.500000+00:00
VLG7104_1400  2019-10-09 17:57:57+00:00  2019-10-09 18:04:00.750000+00:00
WGT8H_2180    2019-11-15 14:09:51+00:00         2019-11-15 14:14:57+00:00
VLG901P_1286  2019-10-18 05:46:30+00:00  2019-10-18 05:52:44.250000+00:00

                                                \
                                           50%
flight_id
AAL136_37370  2019-11-06 13:14:25.500000+00:00
AAL38_36464          2019-10-10 06:26:42+00:00
AAL50_36740          2019-11-28 09:02:45+00:00
AAL104_36539  2019-10-15 10:25:13.500000+00:00
AAL142_37423         2019-10-16 20:29:42+00:00
...                                        ...
VLG7104_1397         2019-10-05 18:13:48+00:00
VOR09_25067          2019-11-30 00:24:03+00:00
VLG7104_1400  2019-10-09 18:10:04.500000+00:00
WGT8H_2180           2019-11-15 14:20:03+00:00
VLG901P_1286  2019-10-18 05:58:58.500000+00:00


                                           75%                        max
flight_id
AAL136_37370  2019-11-06 13:18:50.250000+00:00  2019-11-06 13:23:15+00:00
AAL38_36464          2019-10-10 06:31:42+00:00  2019-10-10 06:36:42+00:00
AAL50_36740   2019-11-28 09:08:55.500000+00:00  2019-11-28 09:15:03+00:00
AAL104_36539  2019-10-15 10:31:48.750000+00:00  2019-10-15 10:38:24+00:00
AAL142_37423         2019-10-16 20:34:27+00:00  2019-10-16 20:39:12+00:00
...                                        ...                        ...
VLG7104_1397  2019-10-05 18:17:28.500000+00:00  2019-10-05 18:21:09+00:00
VOR09_25067   2019-11-30 00:29:19.500000+00:00  2019-11-30 00:34:36+00:00
VLG7104_1400  2019-10-09 18:16:08.250000+00:00  2019-10-09 18:22:12+00:00
WGT8H_2180           2019-11-15 14:25:09+00:00  2019-11-15 14:30:15+00:00
VLG901P_1286  2019-10-18 06:05:09.750000+00:00  2019-10-18 06:11:21+00:00

[38550 rows x 7 columns]

In [11]:
min_vals = groups.min()
max_vals = groups.max()
min_vals['flight_id_col'] = min_vals.index
max_vals['flight_id_col'] = max_vals.index

In [13]:
day_grouper = pd.Grouper(key='timestamp', freq='D')
start_groups = min_vals.groupby(day_grouper,sort=True)
end_groups = max_vals.groupby(day_grouper,sort=True)

In [22]:
i = 0
for key in start_groups.groups.keys():
    starting = start_groups.get_group(key)
    ending = end_groups.get_group(key)
    interval = starting.merge(ending, on='flight_id', how='outer', suffixes=('_start', '_end')).drop(columns=['flight_id_col_start', 'flight_id_col_end'])
    print(interval)
    i += 1
    
    daydata = pd.read_parquet("data/EGLL_dataset.parquet.gz",filters=[('flight_id', 'in', interval.index)])
    print(daydata)
    if i > 5:
        break

                        timestamp_start             timestamp_end
flight_id
AAL100_36765  2019-10-01 04:19:18+00:00 2019-10-01 05:02:21+00:00
AAL104_36613  2019-10-01 09:13:12+00:00 2019-10-01 09:40:42+00:00
AAL106_37017  2019-10-01 05:30:15+00:00 2019-10-01 05:57:18+00:00
AAL108_36670  2019-10-01 10:00:51+00:00 2019-10-01 10:21:09+00:00
AAL136_36551  2019-10-01 12:29:00+00:00 2019-10-01 12:49:30+00:00
...                                 ...                       ...
VIR462M_21631 2019-10-01 06:19:06+00:00 2019-10-01 06:45:12+00:00
VIR4C_14076   2019-10-01 04:26:45+00:00 2019-10-01 05:03:42+00:00
VIR6J_21313   2019-10-01 05:28:15+00:00 2019-10-01 05:53:18+00:00
VIR8E_21097   2019-10-01 07:00:30+00:00 2019-10-01 07:21:45+00:00
VLG7104_1399  2019-10-01 19:44:39+00:00 2019-10-01 20:03:51+00:00

[607 rows x 2 columns]
                    timestamp  altitude callsign  groundspeed  icao24  \
2   2019-10-01 20:11:24+00:00   14900.0   AAL142        417.0  aace5c
3   2019-10-01 20:11:27+00:00   14900.0   AAL142        416.0  aace5c
4   2019-10-01 20:11:30+00:00   14900.0   AAL142        416.0  aace5c
5   2019-10-01 20:11:33+00:00   14900.0   AAL142        416.0  aace5c
6   2019-10-01 20:11:36+00:00   14900.0   AAL142        413.0  aace5c
..                        ...       ...      ...          ...     ...
382 2019-10-01 20:03:39+00:00     625.0  VLG7104        135.0  345643
383 2019-10-01 20:03:42+00:00     575.0  VLG7104        134.0  345643
384 2019-10-01 20:03:45+00:00     550.0  VLG7104        134.0  345643
385 2019-10-01 20:03:48+00:00     525.0  VLG7104        134.0  345643
386 2019-10-01 20:03:51+00:00     475.0  VLG7104        134.0  345643

      latitude  longitude origin squawk      track  vertical_rate  \
2    51.391715  -1.766739   KJFK   7654  95.368655        -2304.0
3    51.391113  -1.756328   KJFK   7654  95.381547        -1984.0
4    51.390691  -1.748962   KJFK   7654  95.381547        -1984.0
5    51.390060  -1.738586   KJFK   7654  95.407517        -1984.0
6    51.389648  -1.731312   KJFK   7654  95.420595        -1984.0
..         ...        ...    ...    ...        ...            ...
382  51.477493  -0.505223    NaN   5325  89.572427         -704.0
383  51.477511  -0.502167    NaN   5325  89.572427         -704.0
384  51.477511  -0.499191    NaN   5325  89.572427         -704.0
385  51.477511  -0.496750    NaN   5325  90.000000         -704.0
386  51.477493  -0.493123    NaN   5325  90.000000         -640.0

        flight_id
2    AAL142_37405
3    AAL142_37405
4    AAL142_37405
5    AAL142_37405
6    AAL142_37405
..            ...
382  VLG7104_1399
383  VLG7104_1399
384  VLG7104_1399
385  VLG7104_1399
386  VLG7104_1399

[298354 rows x 12 columns]
                        timestamp_start             timestamp_end
flight_id
AAL100_36684  2019-10-02 04:22:51+00:00 2019-10-02 05:03:48+00:00
AAL104_36666  2019-10-02 08:40:51+00:00 2019-10-02 09:06:24+00:00
AAL106_36823  2019-10-02 05:19:54+00:00 2019-10-02 05:43:48+00:00
AAL108_36519  2019-10-02 09:13:33+00:00 2019-10-02 09:48:06+00:00
AAL136_36755  2019-10-02 12:07:06+00:00 2019-10-02 12:27:15+00:00
...                                 ...                       ...
VIR462M_21138 2019-10-02 06:25:09+00:00 2019-10-02 06:45:39+00:00
VIR4C_14077   2019-10-02 04:31:24+00:00 2019-10-02 05:06:36+00:00
VIR6J_20771   2019-10-02 05:31:39+00:00 2019-10-02 05:52:54+00:00
VIR8E_21320   2019-10-02 06:37:12+00:00 2019-10-02 06:57:51+00:00
VLG7104_1353  2019-10-02 18:17:48+00:00 2019-10-02 18:40:39+00:00

[656 rows x 2 columns]
                    timestamp  altitude callsign  groundspeed  icao24  \
2   2019-10-02 20:32:27+00:00   16700.0   AAL142        424.0  aab812
3   2019-10-02 20:32:30+00:00   16700.0   AAL142        424.0  aab812
4   2019-10-02 20:32:33+00:00   16700.0   AAL142        426.0  aab812
5   2019-10-02 20:32:36+00:00   16700.0   AAL142        425.0  aab812
6   2019-10-02 20:32:39+00:00   16700.0   AAL142        425.0  aab812
..                        ...       ...      ...          ...     ...
456 2019-10-02 18:40:27+00:00     100.0  VLG7104        131.0  344644
457 2019-10-02 18:40:30+00:00      75.0  VLG7104        131.0  344644
458 2019-10-02 18:40:33+00:00      50.0  VLG7104        131.0  344644
459 2019-10-02 18:40:36+00:00       0.0  VLG7104        131.0  344644
460 2019-10-02 18:40:39+00:00       0.0  VLG7104        131.0  344644

      latitude  longitude origin squawk       track  vertical_rate  \
2    52.137909  -1.238403   KJFK   6304  133.663341        -2240.0
3    52.135061  -1.233608   KJFK   6304  133.667780        -2240.0
4    52.130174  -1.225289   KJFK   6304  133.667780        -2240.0
5    52.126775  -1.219482   KJFK   6304  133.760850        -1984.0
6    52.122467  -1.212184   KJFK   6304  133.854237        -1792.0
..         ...        ...    ...    ...         ...            ...
456  51.465042  -0.416738   LEBL   5325  270.000000         -640.0
457  51.465035  -0.419540   LEBL   5325  270.000000         -640.0
458  51.465035  -0.422592   LEBL   5325  270.000000         -640.0
459  51.464989  -0.425720   LEBL   5325  269.562636         -640.0
460  51.464996  -0.428541   LEBL   5325  269.562636         -640.0

        flight_id
2    AAL142_37317
3    AAL142_37317
4    AAL142_37317
5    AAL142_37317
6    AAL142_37317
..            ...
456  VLG7104_1353
457  VLG7104_1353
458  VLG7104_1353
459  VLG7104_1353
460  VLG7104_1353

[292690 rows x 12 columns]
                       timestamp_start             timestamp_end
flight_id
AAL100_36535 2019-10-03 04:26:30+00:00 2019-10-03 05:01:30+00:00
AAL104_36667 2019-10-03 08:44:45+00:00 2019-10-03 09:07:51+00:00
AAL106_36929 2019-10-03 06:01:51+00:00 2019-10-03 06:22:48+00:00
AAL108_36769 2019-10-03 09:58:21+00:00 2019-10-03 10:26:21+00:00
AAL136_36716 2019-10-03 12:27:27+00:00 2019-10-03 12:45:12+00:00
...                                ...                       ...
VIR450_22364 2019-10-03 05:16:45+00:00 2019-10-03 05:48:48+00:00
VIR454_17832 2019-10-03 09:10:54+00:00 2019-10-03 09:37:27+00:00
VIR4C_18252  2019-10-03 04:42:24+00:00 2019-10-03 05:12:27+00:00
VIR6J_20726  2019-10-03 05:43:12+00:00 2019-10-03 06:06:12+00:00
VIR8E_22470  2019-10-03 07:03:00+00:00 2019-10-03 07:32:24+00:00

[647 rows x 2 columns]
                    timestamp  altitude callsign  groundspeed  icao24  \
3   2019-10-03 08:44:45+00:00   20000.0   AAL104        375.0  a9c508
4   2019-10-03 08:44:48+00:00   20000.0   AAL104        376.0  a9c508
5   2019-10-03 08:44:51+00:00   20000.0   AAL104        376.0  a9c508
6   2019-10-03 08:44:54+00:00   20000.0   AAL104        376.0  a9c508
7   2019-10-03 08:44:57+00:00   20000.0   AAL104        376.0  a9c508
..                        ...       ...      ...          ...     ...
586 2019-10-03 07:32:12+00:00     175.0    VIR8E        155.0  4073ce
587 2019-10-03 07:32:15+00:00     150.0    VIR8E        155.0  4073ce
588 2019-10-03 07:32:18+00:00     100.0    VIR8E        155.0  4073ce
589 2019-10-03 07:32:21+00:00      50.0    VIR8E        155.0  4073ce
590 2019-10-03 07:32:24+00:00      25.0    VIR8E        155.0  4073ce

      latitude  longitude origin squawk       track  vertical_rate  \
3    52.101791  -1.305923   KJFK   1406  139.431834            0.0
4    52.098129  -1.300735   KJFK   1406  139.316028            0.0
5    52.093414  -1.294174   KJFK   1406  139.316028            0.0
6    52.089952  -1.289403   KJFK   1406  139.316028            0.0
7    52.086411  -1.284409   KJFK   1406  139.316028            0.0
..         ...        ...    ...    ...         ...            ...
586  51.477744  -0.411835   KLAX   7653  269.630355         -832.0
587  51.477722  -0.415625   KLAX   7653  269.630355         -832.0
588  51.477697  -0.419388   KLAX   7653  269.630355         -832.0
589  51.477676  -0.422974   KLAX   7653  269.630355         -832.0
590  51.477697  -0.426102   KLAX   7623  269.630355         -832.0

        flight_id
3    AAL104_36667
4    AAL104_36667
5    AAL104_36667
6    AAL104_36667
7    AAL104_36667
..            ...
586   VIR8E_22470
587   VIR8E_22470
588   VIR8E_22470
589   VIR8E_22470
590   VIR8E_22470

[291131 rows x 12 columns]
                       timestamp_start             timestamp_end
flight_id
AAL100_36623 2019-10-04 04:15:51+00:00 2019-10-04 04:42:06+00:00
AAL104_36668 2019-10-04 08:56:45+00:00 2019-10-04 09:30:30+00:00
AAL106_37018 2019-10-04 05:48:54+00:00 2019-10-04 06:19:06+00:00
AAL108_36584 2019-10-04 09:34:12+00:00 2019-10-04 10:13:00+00:00
AAL136_36734 2019-10-04 12:33:18+00:00 2019-10-04 12:57:33+00:00
...                                ...                       ...
VIR4C_14078  2019-10-04 04:25:54+00:00 2019-10-04 05:06:21+00:00
VIR653_15005 2019-10-04 07:22:42+00:00 2019-10-04 07:55:54+00:00
VIR6J_20688  2019-10-04 05:14:09+00:00 2019-10-04 05:49:15+00:00
VIR8E_21802  2019-10-04 06:53:51+00:00 2019-10-04 07:31:24+00:00
VLG7104_1354 2019-10-04 18:12:51+00:00 2019-10-04 18:30:48+00:00

[653 rows x 2 columns]
                    timestamp  altitude callsign  groundspeed  icao24  \
2   2019-10-04 08:56:45+00:00   15975.0   AAL104        372.0  a9c508
3   2019-10-04 08:56:48+00:00   15975.0   AAL104        372.0  a9c508
4   2019-10-04 08:56:51+00:00   15975.0   AAL104        372.0  a9c508
5   2019-10-04 08:56:54+00:00   15975.0   AAL104        372.0  a9c508
6   2019-10-04 08:56:57+00:00   15975.0   AAL104        371.0  a9c508
..                        ...       ...      ...          ...     ...
357 2019-10-04 18:30:36+00:00     450.0  VLG7104        130.0  344644
358 2019-10-04 18:30:39+00:00     425.0  VLG7104        131.0  344644
359 2019-10-04 18:30:42+00:00     400.0  VLG7104        131.0  344644
360 2019-10-04 18:30:45+00:00     350.0  VLG7104        132.0  344644
361 2019-10-04 18:30:48+00:00     325.0  VLG7104        132.0  344644

      latitude  longitude origin squawk       track  vertical_rate  \
2    51.402054  -1.772733   KJFK   6337  102.879287         -128.0
3    51.400700  -1.763687   KJFK   6337  103.029195          -64.0
4    51.399536  -1.755660   KJFK   6337  103.063954          -64.0
5    51.398372  -1.747589   KJFK   6337  103.063954            0.0
6    51.397247  -1.739848   KJFK   6337  103.098896           64.0
..         ...        ...    ...    ...         ...            ...
357  51.465035  -0.418167    NaN   5324  269.559272         -640.0
358  51.464989  -0.421219    NaN   5324  269.562636         -640.0
359  51.464989  -0.423584    NaN   5324  269.562636         -640.0
360  51.464951  -0.427056    NaN   5324  269.565949         -640.0
361  51.464942  -0.429840    NaN   5324  269.565949         -576.0

        flight_id
2    AAL104_36668
3    AAL104_36668
4    AAL104_36668
5    AAL104_36668
6    AAL104_36668
..            ...
357  VLG7104_1354
358  VLG7104_1354
359  VLG7104_1354
360  VLG7104_1354
361  VLG7104_1354

[326776 rows x 12 columns]
                        timestamp_start             timestamp_end
flight_id
AAL100_36744  2019-10-05 04:22:15+00:00 2019-10-05 05:02:45+00:00
AAL104_36583  2019-10-05 08:24:12+00:00 2019-10-05 08:50:33+00:00
AAL106_36921  2019-10-05 05:23:03+00:00 2019-10-05 05:47:09+00:00
AAL108_36564  2019-10-05 10:30:57+00:00 2019-10-05 10:45:42+00:00
AAL136_36460  2019-10-05 12:40:48+00:00 2019-10-05 12:57:15+00:00
...                                 ...                       ...
VIR462M_20770 2019-10-05 06:31:27+00:00 2019-10-05 06:55:21+00:00
VIR4C_18253   2019-10-05 04:45:54+00:00 2019-10-05 05:17:48+00:00
VIR6J_21314   2019-10-05 05:59:18+00:00 2019-10-05 06:18:30+00:00
VIR8E_20689   2019-10-05 07:30:09+00:00 2019-10-05 07:53:12+00:00
VLG7104_1397  2019-10-05 18:06:27+00:00 2019-10-05 18:21:09+00:00

[623 rows x 2 columns]
                    timestamp  altitude callsign  groundspeed  icao24  \
3   2019-10-05 04:22:15+00:00   15225.0   AAL100        368.0  a9d640
4   2019-10-05 04:22:18+00:00   15225.0   AAL100        367.0  a9d640
5   2019-10-05 04:22:21+00:00   15225.0   AAL100        367.0  a9d640
6   2019-10-05 04:22:24+00:00   15225.0   AAL100        366.0  a9d640
7   2019-10-05 04:22:27+00:00   15225.0   AAL100        366.0  a9d640
..                        ...       ...      ...          ...     ...
293 2019-10-05 18:20:57+00:00     325.0  VLG7104        136.0  345614
294 2019-10-05 18:21:00+00:00     300.0  VLG7104        136.0  345614
295 2019-10-05 18:21:03+00:00     250.0  VLG7104        137.0  345614
296 2019-10-05 18:21:06+00:00     225.0  VLG7104        137.0  345614
297 2019-10-05 18:21:09+00:00     175.0  VLG7104        137.0  345614

      latitude  longitude origin squawk       track  vertical_rate  \
3    51.404709  -1.770432   KJFK   5434  104.149476        -1344.0
4    51.403610  -1.763578   KJFK   5434  104.338793        -1344.0
5    51.402283  -1.755214   KJFK   5434  104.338793        -1280.0
6    51.400933  -1.746750   KJFK   5434  104.377511        -1280.0
7    51.399722  -1.738892   KJFK   5434  104.225964        -1280.0
..         ...        ...    ...    ...         ...            ...
293  51.477418  -0.506439    NaN   5332   89.578715         -704.0
294  51.477448  -0.503293    NaN   5332   89.578715         -704.0
295  51.477465  -0.500183    NaN   5332   89.581790         -704.0
296  51.477493  -0.497131    NaN   5332   89.581790         -704.0
297  51.477511  -0.493851    NaN   5332   89.581790         -640.0

        flight_id
3    AAL100_36744
4    AAL100_36744
5    AAL100_36744
6    AAL100_36744
7    AAL100_36744
..            ...
293  VLG7104_1397
294  VLG7104_1397
295  VLG7104_1397
296  VLG7104_1397
297  VLG7104_1397

[265989 rows x 12 columns]
                        timestamp_start             timestamp_end
flight_id
AAL100_36685  2019-10-06 04:09:51+00:00 2019-10-06 05:03:18+00:00
AAL104_36518  2019-10-06 08:50:36+00:00 2019-10-06 09:15:00+00:00
AAL106_37303  2019-10-06 07:08:15+00:00 2019-10-06 07:41:45+00:00
AAL108_36631  2019-10-06 10:36:06+00:00 2019-10-06 11:02:45+00:00
AAL136_36500  2019-10-06 13:08:42+00:00 2019-10-06 13:38:15+00:00
...                                 ...                       ...
VIR462M_21265 2019-10-06 06:08:21+00:00 2019-10-06 06:41:24+00:00
VIR4C_18556   2019-10-06 04:32:00+00:00 2019-10-06 05:15:21+00:00
VIR6J_20772   2019-10-06 04:45:27+00:00 2019-10-06 05:20:36+00:00
VIR8E_21189   2019-10-06 06:59:24+00:00 2019-10-06 07:28:45+00:00
VLG7104_1398  2019-10-06 18:16:24+00:00 2019-10-06 18:44:54+00:00

[661 rows x 2 columns]
                    timestamp  altitude callsign  groundspeed  icao24  \
3   2019-10-06 09:47:42+00:00   34000.0   AAL235        439.0  aad981
4   2019-10-06 09:47:45+00:00   34000.0   AAL235        439.0  aad981
5   2019-10-06 09:47:48+00:00   34000.0   AAL235        439.0  aad981
6   2019-10-06 09:47:51+00:00   34000.0   AAL235        439.0  aad981
7   2019-10-06 09:47:54+00:00   34000.0   AAL235        439.0  aad981
..                        ...       ...      ...          ...     ...
568 2019-10-06 18:44:42+00:00     350.0  VLG7104        128.0  345614
569 2019-10-06 18:44:45+00:00     300.0  VLG7104        128.0  345614
570 2019-10-06 18:44:48+00:00     275.0  VLG7104        129.0  345614
571 2019-10-06 18:44:51+00:00     250.0  VLG7104        129.0  345614
572 2019-10-06 18:44:54+00:00     200.0  VLG7104        129.0  345614

      latitude  longitude origin squawk       track  vertical_rate  \
3    51.406815   0.848323   LIRF   5775  327.939272            0.0
4    51.412152   0.842972   LIRF   5775  327.939272            0.0
5    51.417133   0.838013   LIRF   5775  327.939272            0.0
6    51.422287   0.832808   LIRF   5775  327.939272            0.0
7    51.427277   0.827835   LIRF   5775  327.939272            0.0
..         ...        ...    ...    ...         ...            ...
568  51.464996  -0.414882    NaN   5320  270.000000         -640.0
569  51.464989  -0.417709    NaN   5320  270.000000         -640.0
570  51.464996  -0.420079    NaN   5320  270.000000         -640.0
571  51.464996  -0.423567    NaN   5320  270.000000         -640.0
572  51.464989  -0.426712    NaN   5320  270.000000         -640.0

        flight_id
3    AAL235_37457
4    AAL235_37457
5    AAL235_37457
6    AAL235_37457
7    AAL235_37457
..            ...
568  VLG7104_1398
569  VLG7104_1398
570  VLG7104_1398
571  VLG7104_1398
572  VLG7104_1398

[342179 rows x 12 columns]